export const APP_NAME = 'ViewTube';
export const API_BASE_URL = 'https://youtube-vi8f.onrender.com/api';

export const CATEGORIES = ['Music', 'Gaming', 'Spiritual', 'Entertainment', 'Education', 'Vlogs'];

export const TRANSLATIONS = {
    en: {
        home: 'Home',
        explore: 'Explore',
        trending: 'Trending',
        subscriptions: 'Subscriptions',
        history: 'History',
        watchLater: 'Watch Later',
        likedVideos: 'Liked Videos',
        yourChannel: 'Your Channel',
        search: 'Search...',
        subscribe: 'Subscribe',
        subscribed: 'Subscribed',
        unsubscribe: 'Unsubscribe',
        subscribers: 'Subscribers',
        views: 'views',
        about: 'About',
        videos: 'Videos',
        edit: 'Edit',
        delete: 'Delete',
        report: 'Report',
        share: 'Share',
        login: 'Login',
        register: 'Register',
        upload: 'Upload',
        description: 'Description',
        category: 'Category',
        saveChanges: 'Save Changes',
        avatar: 'Avatar',
        addedToWatchLater: 'Added to Watch Later',
        comment: 'Comment',
        comments: 'Comments',
        noSubscriptions: 'No subscriptions yet.',
        noVideos: 'No videos yet.',
        notifications: 'Notifications',
        confirmDelete: 'Are you sure?',
        today: 'Today',
        daysAgo: 'days ago',
        customizeChannel: 'Customize Channel',
        editProfile: 'Edit Profile',
        bannerImage: 'Banner Image',
        aboutMe: 'About',
        bio: 'Bio',
        username: 'Username',
        reportReason: 'Report reason',
        copy: 'Copy',
        cancel: 'Cancel',
        all: 'All',
        gaming: 'Gaming',
        music: 'Music',
        spiritual: 'Spiritual',
        entertainment: 'Entertainment',
        education: 'Education',
        vlogs: 'Vlogs',
        logout: 'Logout',
        usernameCooldown: 'Username can only be changed once every 30 days',
        daysRemaining: 'days remaining',
        waitDays: 'You can change your username in',
        noThumbnail: 'No thumbnail',
        changeThumbnail: 'Change Thumbnail',
        titleReq: 'Title (required)',
        videoDescPlaceholder: 'Tell viewers about your video',
        uploadThumbnail: 'Upload thumbnail',
        uploadThumbDesc: 'Upload your own or generate one with AI below',
        videoLink: 'Video Link',
        fileName: 'File name',
        duration: 'Duration',
        noNotifications: 'No notifications',
        editVideo: 'Edit Video',
        deleteVideo: 'Delete Video',
        saveWatchLater: 'Save to Watch Later',
        analytics: 'Analytics',
        totalViews: 'Total Views',
        totalLikes: 'Total Likes',
        totalVideos: 'Total Videos',
        topVideos: 'Top Videos',
        last28Days: 'Last 28 days',
        last90Days: 'Last 90 days',
        lastYear: 'Last year',
        subscriberGrowth: 'Subscriber Growth',
        viewsOverTime: 'Views Over Time',
        likesOverTime: 'Likes Over Time',
        commentsOverTime: 'Comments Over Time',
        watchHours: 'Watch Hours',
        avgViews: 'Avg Views/Video',
        engagement: 'Engagement'
    },
    hi: {
        home: 'होम',
        explore: 'एक्सप्लोर',
        trending: 'ट्रेंडिंग',
        subscriptions: 'सब्सक्रिप्शन',
        history: 'इतिहास',
        watchLater: 'बाद में देखें',
        likedVideos: 'पसंद किए गए वीडियो',
        yourChannel: 'आपका चैनल',
        search: 'खोजें...',
        subscribe: 'सब्सक्राइब',
        subscribed: 'सब्सक्राइब किया गया',
        unsubscribe: 'अनसब्सक्राइब',
        subscribers: 'सब्सक्राइबर्स',
        views: 'देखें',
        about: 'बारे में',
        videos: 'वीडियो',
        edit: 'संपादन',
        delete: 'हटाएं',
        report: 'रिपोर्ट',
        share: 'साझा करें',
        login: 'लॉगिन',
        register: 'रजिस्टर',
        upload: 'अपलोड',
        description: 'विवरण',
        category: 'श्रेणी',
        saveChanges: 'बदलाव सहेजें',
        avatar: 'अवतार',
        addedToWatchLater: 'वॉच लेटर में जोड़ा गया',
        comment: 'टिप्पणी',
        comments: 'टिप्पणियां',
        noSubscriptions: 'अभी तक कोई सब्सक्रिप्शन नहीं है।',
        noVideos: 'अभी तक कोई वीडियो नहीं है।',
        notifications: 'नोटिफिकेशन',
        confirmDelete: 'क्या आप निश्चित हैं?',
        today: 'आज',
        daysAgo: 'दिन पहले',
        customizeChannel: 'चैनल कस्टमाइज़ करें',
        editProfile: 'प्रोफ़ाइल संपादित करें',
        bannerImage: 'बैनर इमेज',
        aboutMe: 'बारे में',
        bio: 'बायो',
        username: 'यूज़रनेम',
        reportReason: 'रिपोर्ट का कारण',
        copy: 'कॉपी',
        cancel: 'रद्द करें',
        all: 'सभी',
        gaming: 'गेमिंग',
        music: 'संगीत',
        spiritual: 'आध्यात्मिक',
        entertainment: 'मनोरंजन',
        education: 'शिक्षा',
        vlogs: 'व्लॉग',
        logout: 'लॉगआउट',
        usernameCooldown: 'यूज़रनेम केवल हर 30 दिनों में एक बार बदला जा सकता है',
        daysRemaining: 'दिन शेष',
        waitDays: 'आप अपना यूज़रनेम बदल सकते हैं',
        noThumbnail: 'कोई थंबनेल नहीं',
        changeThumbnail: 'थंबनेल बदलें',
        titleReq: 'शीर्षक (आवश्यक)',
        videoDescPlaceholder: 'दर्शकों को अपने वीडियो के बारे में बताएं',
        uploadThumbnail: 'थंबनेल अपलोड करें',
        uploadThumbDesc: 'अपना खुद का थंबनेल अपलोड करें या नीचे AI से बनाएं',
        videoLink: 'वीडियो लिंक',
        fileName: 'फ़ाइल का नाम',
        duration: 'अवधि',
        noNotifications: 'कोई नोटिफिकेशन नहीं',
        editVideo: 'वीडियो संपादित करें',
        deleteVideo: 'वीडियो हटाएं',
        saveWatchLater: 'बाद में देखने के लिए सेव करें',
        analytics: 'एनालिटिक्स',
        totalViews: 'कुल व्यूज',
        totalLikes: 'कुल लाइक्स',
        totalVideos: 'कुल वीडियो',
        topVideos: 'टॉप वीडियो',
        last28Days: 'पिछले 28 दिन',
        last90Days: 'पिछले 90 दिन',
        lastYear: 'पिछला साल',
        subscriberGrowth: 'सब्सक्राइबर ग्रोथ',
        viewsOverTime: 'समय के साथ व्यूज',
        likesOverTime: 'समय के साथ लाइक्स',
        commentsOverTime: 'समय के साथ टिप्पणियां',
        watchHours: 'वॉच आवर्स',
        avgViews: 'औसत व्यूज/वीडियो',
        engagement: 'एंगेजमेंट'
    }
};
